### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by Naereen** [nicolashainaux/sphinx-autodoc-annotation#7]
Hi.
Could you provide an example of a Python project documented using this extension?
It would help to see that it works in practice.
Kuddo for the project, kind regards.

**Comment by Naereen** [comment]
@nicolashainaux no update?

**Comment by ghost** [comment]
I don't know if this project is used by anybody. I created it, but I ended up never using it.

**Comment by Naereen** [comment]
OK

**Comment by nicolashainaux** [comment]
@Naereen Sorry I've completely missed this issue.
I don't know who else uses it (but there must be some people, I was not the only one).
For a while, a bug was preventing from using it on readthedocs, so I disabled it on my own project. I haven't re-enabled it yet, but I will, at some point, because I find it still useful not to have to type all the `:type ... : ...` and `:rtype: ...` lines.
Anyway there's not much more to see in my project than in the README.

**Comment by Naereen** [comment]
Hi! OK, no issue and don't worry :smile: !

I liked the idea but never used it myself (yet). For one of my large documentation I was even too lazy to write `:type ...:` annotations ...

**Comment by nicolashainaux** [comment]
> For one of my large documentation I was even too lazy to write :type ...: annotations ...

Yeah, this extension reduces the pain, once it works. Hope this is still fine with python 3.6 by the way.

**Comment by Naereen** [comment]
I see no reason for the extension to be broken in Python 3.6 or 3.7, don't worry.
